name: my_project
version: '1.0'
config-version: 2

profile: my_project

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

seed-paths: ["seeds"]

models:
  my_project:
    +materialized: table

seeds:
  my_project:
    merchant_dictionary_full:
      +column_types:
        pattern_regex: text