select
    case
        ------------------------------------------------------------------
        -- HIGH-IMPACT / SPECIFIC FIRST
        ------------------------------------------------------------------
        -- Bilt / Rent / Yardi
        when ct.description ilike '%BPS*BILT%' then 'Bilt'
        when ct.description ilike '%BPS*BILT %' then 'Bilt'
        when ct.description ilike '%BILT %' then 'Bilt'
        when ct.description ilike '%BPS*BILT REWARDS%' then 'Bilt'
        when ct.description ilike '%YSI%' then 'Yardi'

        -- Ova (Natera / Cryovault / Ova)
        when ct.description ilike '%NATERA%' then 'Ova'
        when ct.description ilike '%CRYOVAULT%' then 'Ova'
        when ct.description ilike '% OVA%' or ct.description ilike 'OVA %' then 'Ova'

        -- Amazon ecosystem (collapsed)
        when ct.description ilike 'Prime Video %' then 'Prime Video'
        when ct.description ilike 'Amazon Prime%' and ct.description not ilike '%VIDEO%' then 'Amazon Prime'
        when ct.description ilike 'Amazon Prime*%' and ct.description not ilike '%VIDEO%' then 'Amazon Prime'
        when ct.description ilike 'AMAZON PRIME*%' and ct.description not ilike '%VIDEO%' then 'Amazon Prime'
        when ct.description ilike 'Amazon.com*%' then 'Amazon'
        when ct.description ilike 'AMAZON MKTPL%' then 'Amazon'
        when ct.description ilike 'AMAZON MKTPLACE PMTS%' then 'Amazon'
        when ct.description ilike 'AMZN Mktp%' then 'Amazon'
        when ct.description ilike 'AMZNMktplace%' then 'Amazon'

        -- Whole Foods (all variants)
        when ct.description ilike '%WHOLEFDS%' or ct.description ilike '%WHOLE FOODS%' then 'Whole Foods'

        ------------------------------------------------------------------
        -- GENERAL LONG-TAIL (NON-RESTAURANT FIRST)
        ------------------------------------------------------------------
        when ct.description ilike '%RENDER.COM%' then 'Render'
        when ct.description ilike '%WF WAYFAIR%' then 'Wayfair'
        when ct.description ilike '%WAYFAIR%' then 'Wayfair'
        when ct.description ilike '%NIU TECHNOLOGIES%' or ct.description ilike '%NIU%' then 'NIU Technologies'
        when ct.description ilike '%SP FLUIDFREERIDE.COM%' then 'FluidFreeRide'
        when ct.description ilike '%CURSOR  AI POWERED IDE%' or ct.description ilike '%CURSOR, AI POWERED IDE%' then 'Cursor'
        when ct.description ilike '%CURSOR USAGE %' then 'Cursor'
        when ct.description ilike 'OPENAI *CHATGPT SUBSCR%' or ct.description ilike 'CHATGPT SUBSCRIPTION%' or ct.description ilike 'OPENAI%' then 'OpenAI'
        when ct.description ilike 'GOOGLE *CLOUD%' or ct.description ilike 'Google One%' or ct.description ilike 'GOOGLE *GSUITE%' or ct.description ilike 'GOOGLE *MICROSOFT APPS%' or ct.description ilike 'GOOGLE *MICROSOFT %' then 'Google'
        when ct.description ilike 'Microsoft*Store%' then 'Microsoft Store'
        when ct.description ilike 'APPLE.COM/BILL%' then 'Apple'
        when ct.description ilike 'DNH*GODADDY.COM%' then 'GoDaddy'
        when ct.description ilike 'DIGITALOCEAN.COM%' then 'DigitalOcean'
        when ct.description ilike 'WWW.ZENBUSINESS.COM%' then 'ZenBusiness'
        when ct.description ilike 'ELEVENLABS.IO%' then 'ElevenLabs'
        when ct.description ilike 'LUMA AI DREAM MACHINE%' then 'Luma AI'
        when ct.description ilike 'PADDLE.NET* %' then 'Paddle'
        when ct.description ilike 'XAI LLC%' then 'xAI'
        when ct.description ilike 'TAVILY AI%' then 'Tavily'
        when ct.description ilike 'LIMITLESS%' then 'Limitless'
        when ct.description ilike 'NOTION LABS%' then 'Notion'
        when ct.description ilike 'NYTimes%NYTimes%' or ct.description ilike 'NYTimes%' then 'New York Times'
        when ct.description ilike 'Spotify %' or ct.description ilike 'SPOTIFY %' then 'Spotify'
        when ct.description ilike 'NETFLIX%' or ct.description ilike 'Netflix%' or ct.description ilike 'NETFLIX, INC.%' then 'Netflix'
        when ct.description ilike 'DIVVYBI*SUBSCRIPTION%' then 'Divvy Bikes'
        when ct.description ilike 'HARVARD BUS HBR.ORG%' then 'Harvard Business Review'
        when ct.description ilike 'LinkedInPreA %' then 'LinkedIn Premium'
        when ct.description ilike 'TWITTER PAID FEATURES%' then 'Twitter (Paid)'
        when ct.description ilike 'RENDER.COM%' then 'Render'
        when ct.description ilike 'PRINTWITHME%' then 'PrintWithMe'
        when ct.description ilike 'INTEREST CHARGE ON PURCHASES%' then 'Card Interest'
        when ct.description ilike 'LATE FEE%' then 'Card Late Fee'

        ------------------------------------------------------------------
        -- MEDICAL / HEALTH
        ------------------------------------------------------------------
        when ct.description ilike '%UNIVERSITY OF CHICAGO%' then 'UChicago Medicine'
        when ct.description ilike '%ATHLETICO%' then 'Athletico'
        when ct.description ilike '%LAKE ANESTHESIA ASSOCIATE%' then 'Lake Anesthesia'
        when ct.description ilike '%PURE DENTAL SPA%' then 'Pure Dental Spa'
        when ct.description ilike 'WALGREENS %' then 'Walgreens'
        when ct.description ilike 'CVS/PHARMACY %' or ct.description ilike 'CVS %' then 'CVS'
        when ct.description ilike '%LIVE LEAN RX%' then 'Live Lean RX'

        ------------------------------------------------------------------
        -- RIDESHARE / DELIVERY
        ------------------------------------------------------------------
        when ct.description ilike 'UBER   *EATS%' or ct.description ilike 'UBER *EATS%' then 'Uber Eats'
        when ct.description ilike 'UBER%TRIP%' or ct.description ilike 'UBER   TRIP%' or ct.description ilike 'UBER *TRIP%' then 'Uber'
        when ct.description ilike 'UBER   *ONE%' then 'Uber One'
        when ct.description ilike 'LYFT%' then 'Lyft'
        when ct.description ilike 'DOORDASH*%' or ct.description ilike 'DD *DOORDASH%' or ct.description ilike 'DD DOORDASH%' then 'DoorDash'
        when ct.description ilike 'IC* INSTACART%' then 'Instacart'

        ------------------------------------------------------------------
        -- TRANSIT / PARKING / TOLLS
        ------------------------------------------------------------------
        when ct.description ilike 'VENTRA ACCOUNT%' then 'Ventra'
        when ct.description ilike 'MTA*NYCT PAYGO%' then 'MTA Subway'
        when ct.description ilike 'MTA*LIRR %' or ct.description ilike 'MTA*LIRR ONBOARD%' then 'MTA LIRR'
        when ct.description ilike 'TFL TRAVEL CH%' then 'TfL'
        when ct.description ilike 'HEATHROW EXPRESS%' then 'Heathrow Express'
        when ct.description ilike 'SPOTHERO %' then 'SpotHero'
        when ct.description ilike 'PARK CHICAGO MOBILE%' then 'ParkChicago'
        when ct.description ilike 'METROPOLIS PARKING%' then 'Metropolis Parking'
        when ct.description ilike 'INTERPARK LLC%' then 'InterPark'
        when ct.description ilike 'ParkWhiz %' then 'ParkWhiz'
        when ct.description ilike 'O''HARE INT. AIRPORT PARK%' or ct.description ilike 'LOT A EPS%' then 'O''Hare Parking'
        when ct.description ilike 'CH312 - MART PARC - ORLE%' or ct.description ilike 'CH418 - WABASH-RANDOLPH%' or ct.description ilike 'CH312 -  MART PARC ORLEA%' or ct.description ilike 'CH312 - MART PARC - OR CHICAGO      ,IL%' then 'Mart Parc Parking'
        when ct.description ilike 'SLC PARKING STATIONS%' then 'SLC Parking'
        when ct.description ilike 'LOT D PAY ON FOOT%' then 'Lot D Parking'
        when ct.description ilike '%PARK CHICAGO%' then 'ParkChicago'
        when ct.description ilike 'PARKINGMETER4 8772427901%' then 'Parking Meter'
        when ct.description ilike 'IL TOLLWAY-WEB-UNPD TOLL%' or ct.description ilike 'IL TOLLWAY%' then 'Illinois Tollway'
        when ct.description ilike 'DUBAI TAXI%' then 'Dubai Taxi'
        when ct.description ilike 'LICENSED TAXI%' then 'Licensed Taxi'
        when ct.description ilike 'CURB %TAXI%' or ct.description ilike 'CURB NYC TAXI%' or ct.description ilike 'CURB CHICAGO TAXI%' or ct.description ilike 'CURB NEW YORK TAXI%' then 'Curb Taxi'
        when ct.description ilike 'NYC TAXI %' then 'NYC Taxi'
        when ct.description ilike 'TXW%LONDON TAXI%' then 'London Taxi'
        when ct.description ilike 'CMT %CHICAGO%' or ct.description ilike 'CMT CHICAGO %' then 'CMT Taxi'
        when ct.description ilike 'CMT UK LTD TAXI FARE%' then 'CMT Taxi'
        when ct.description ilike 'CAREEM HALA%' or ct.description ilike 'CAREEM RIDE%' then 'Careem'
        when ct.description ilike 'CAREEM FOOD%' then 'Careem Food'
        when ct.description ilike 'CAREEM QUIK%' then 'Careem Quik'
        when ct.description ilike 'LIM*RIDE %' or ct.description ilike 'LIM*4 RIDES %' or ct.description ilike 'LIM*RIDE COST%' then 'Lime'
        when ct.description ilike 'HEATHROW BUDWEISER T3%' or ct.description ilike 'HWH DX19 BUDWEISER T3%' then 'Heathrow T3 Budweiser'

        ------------------------------------------------------------------
        -- AIRLINES / LODGING / TRAVEL BOOKING
        ------------------------------------------------------------------
        when ct.description ilike 'AMERICAN AIR%' or ct.description ilike 'AMERICAN AI %' or ct.description ilike 'AA Kiosk%' or ct.description ilike 'AA.COM %' or ct.description ilike 'AMERICANAIRLINES PAC USD%' then 'American Airlines'
        when ct.description ilike 'UA INFLT%' then 'United Airlines'
        when ct.description ilike 'DELTA AIR%' or ct.description ilike 'DELTA AIR   %' then 'Delta Air Lines'
        when ct.description ilike 'BRITISH A %' or ct.description ilike 'BA INFLIGHT SALES%' or ct.description ilike 'B A INTERNET%' then 'British Airways'
        when ct.description ilike 'EMIRATES%' then 'Emirates'
        when ct.description ilike '%KENYA AIR%' or ct.description ilike '%KENYA AIRWAYS%' or ct.description ilike 'KQ CC %' then 'Kenya Airways'
        when ct.description ilike '%KENYA ETA%' then 'Kenya eTA'
        when ct.description ilike 'EASYJET IN F%' then 'easyJet'
        when ct.description ilike 'AIR MARGARITAVILLE-%' then 'Air Margaritaville'
        when ct.description ilike 'AIRBNB %' or ct.description ilike 'AIRBNB* %' then 'Airbnb'
        when ct.description ilike 'BKG*BOOKING.COM HOTEL%' or ct.description ilike 'BOOKING.COM%' or ct.description ilike 'Cars on Booking%' then 'Booking.com'
        when ct.description ilike 'ALAMO RENT-A-CAR%' then 'Alamo Rent A Car'
        when ct.description ilike '%EFAY RENT A CAR%' or ct.description ilike '%EFAY%' then 'EFAY Rent A Car'
        when ct.description ilike 'LE MERIDIEN MINA SEYAHI%' then 'Le Meridien Mina Seyahi'
        when ct.description ilike 'MARRIOTT JW MARQUIS%' then 'JW Marriott Marquis'
        when ct.description ilike 'GRAND MILLENNIUM HOTEL%' then 'Grand Millennium'
        when ct.description ilike '%MODERNHAUS%' then 'Modernhaus Soho'
        when ct.description ilike 'SOFITEL NEW YORK%' then 'Sofitel New York'
        when ct.description ilike 'TRADEMARK HOTEL%' then 'Trademark Hotel'
        when ct.description ilike 'HOTEL FRAYE%' then 'Hotel Fraye'
        when ct.description ilike 'ATLANTA AIRPORT%' then 'Atlanta Airport'
        when ct.description ilike 'GR CNYN MASWIK DEPOSIT%' or ct.description ilike 'MASWIK CAFE/PIZZA PUB%' then 'Grand Canyon Maswik'
        when ct.description ilike 'GRAND CANYON NATIONAL P%' then 'Grand Canyon National Park'

        ------------------------------------------------------------------
        -- GROCERIES / MARKETS
        ------------------------------------------------------------------
        when ct.description ilike 'MARIANOS %' then 'Mariano''s'
        when ct.description ilike 'JOONG BOO MARKET%' then 'Joong Boo Market'
        when ct.description ilike 'EATALY %' or ct.description ilike 'EATALY CHICAGO %' or ct.description ilike 'EATALY FIDI %' then 'Eataly'
        when ct.description ilike 'CARREFOUR %' or ct.description ilike 'CARREFOUR VILLAGE MARKET%' or ct.description ilike 'MAF % TILL %' then 'Carrefour'
        when ct.description ilike 'TESCO STORES %' then 'Tesco'
        when ct.description ilike 'SAINSBURYS %' then 'Sainsbury''s'
        when ct.description ilike 'M&S SIMPLY FOOD%' or ct.description ilike 'MARKS&SPENCER %' or ct.description ilike 'MARKS%SPENCER PLC%' or ct.description ilike 'M&S SIMPLY FOOD - SSP%' then 'Marks & Spencer'
        when ct.description ilike 'WAITROSE %' then 'Waitrose'
        when ct.description ilike '%Misfits Market%' then 'Misfits Market'
        when ct.description ilike 'SMITH''S MRKTPL %' then 'Smith''s Marketplace'
        when ct.description ilike 'CO-OP GROUP %' then 'Co-op'

        ------------------------------------------------------------------
        -- COFFEE / QUICK SERVE
        ------------------------------------------------------------------
        when ct.description ilike 'STARBUCKS %' then 'Starbucks'
        when ct.description ilike 'PRET A MANGER%' then 'Pret A Manger'
        when ct.description ilike 'PEET''S %' then 'Peet''s Coffee'
        when ct.description ilike 'SQ *BLUE BOTTLE COFFEE%' then 'Blue Bottle Coffee'
        when ct.description ilike 'SQ *NOW OR NEVER COFFEE%' then 'Now or Never Coffee'
        when ct.description ilike 'SQ *HASIB COFFEE%' then 'Hasib Coffee'
        when ct.description ilike 'TST*INTELLIGENTSIA %' or ct.description ilike 'TST* INTELLIGENTSIA %' then 'Intelligentsia Coffee'
        when ct.description ilike 'SQ *FAIRGROUNDS %' then 'Fairgrounds Coffee'
        when ct.description ilike 'SQ *GROUND CENTRAL COFFEE%' then 'Ground Central Coffee'
        when ct.description ilike 'SQ *LA COLOMBE%' then 'La Colombe'
        when ct.description ilike 'CAFFE NERO %' then 'Caffè Nero'
        when ct.description ilike 'OLD COFFEE HOUSE%' then 'Old Coffee House'
        when ct.description ilike 'THE BLACK PENNY%' then 'The Black Penny'
        when ct.description ilike 'OSEYO%' then 'Oseyo'

        ------------------------------------------------------------------
        -- FAST FOOD / CHAINS
        ------------------------------------------------------------------
        when ct.description ilike 'MCDONALD%''S%' or ct.description ilike 'MCDONALDS%' then 'McDonald''s'
        when ct.description ilike 'DUNKIN %' then 'Dunkin'''
        when ct.description ilike 'ARBYS %' then 'Arby''s'
        when ct.description ilike 'DOMINO''S%' then 'Domino''s'
        when ct.description ilike 'KFC%' or ct.description ilike 'KFC - %' then 'KFC'
        when ct.description ilike 'TGI FRIDAYS%' then 'TGI Friday''s'
        when ct.description ilike 'HATTIE B%''S%' or ct.description ilike 'HATTIE BS%' then 'Hattie B''s'
        when ct.description ilike 'MELLOW MUSHROOM%' then 'Mellow Mushroom'
        when ct.description ilike 'NATHANS%' then 'Nathan''s'
        when ct.description ilike 'AUNTIE ANNES%' or ct.description ilike 'MSP AIRP AUNTIE ANNES%' then 'Auntie Anne''s'

        ------------------------------------------------------------------
        -- RESTAURANTS (NAMED)
        ------------------------------------------------------------------
        when ct.description ilike '%MAPLE & ASH%' or ct.description ilike '%MAPLE &amp; ASH%' then 'Maple & Ash'
        when ct.description ilike 'GIRL & THE GOAT%' or ct.description ilike 'GIRL &amp; THE GOAT%' then 'Girl & The Goat'
        when ct.description ilike 'GIBSONS ITALIA%' then 'Gibsons Italia'
        when ct.description ilike 'GIBSONS HUGOS%' then 'Gibsons Hugo''s'
        when ct.description ilike 'WEST LOOP MARKET - MAD%' or ct.description ilike 'WEST LOOP MARKET%' then 'West Loop Market'
        when ct.description ilike 'LE COLONIAL OAK STREET%' then 'Le Colonial'
        when ct.description ilike 'THE PALOMAR%' then 'The Palomar'
        when ct.description ilike 'PYLOS RESTAURANT%' then 'Pylos'
        when ct.description ilike 'THE EAST POLE%' then 'The East Pole'
        when ct.description ilike 'DOC BS RESTAURANT%' then 'Doc B''s'
        when ct.description ilike 'BEAUTY & ESSEX%' then 'Beauty & Essex'
        when ct.description ilike 'ZUMA RESTAURANTS%' then 'Zuma'
        when ct.description ilike 'BOB BOB RICARD%' then 'Bob Bob Ricard'
        when ct.description ilike 'HOPPERS SOHO%' then 'Hoppers Soho'
        when ct.description ilike 'PERA SOHO%' then 'Pera Soho'
        when ct.description ilike 'BRINDISA SOHO%' then 'Brindisa Soho'
        when ct.description ilike 'LIBERTY%' then 'Liberty London'
        when ct.description ilike 'My Place Soho%' then 'My Place Soho'
        when ct.description ilike 'James Elliott Butchers%' then 'James Elliott Butchers'
        when ct.description ilike 'ROCCA%' then 'Rocca'
        when ct.description ilike 'RED DOOR SALOON%' then 'Red Door Saloon'
        when ct.description ilike 'TAVERNA DOMAIN%' then 'Taverna - The Domain'
        when ct.description ilike 'ORD HUB 51%' or ct.description ilike 'HUB 51%' then 'Hub 51'
        when ct.description ilike 'Broken English Taco Pub%' then 'Broken English Taco Pub'
        when ct.description ilike 'LOGS AND EMBERS REST%' then 'Logs and Embers'
        when ct.description ilike 'SQ *SHOTSHAK%' then 'Shotshak'
        when ct.description ilike 'CASA DE SONIA%' then 'Casa de Sonia'
        when ct.description ilike 'THE DUCK HOOK%' then 'The Duck Hook'
        when ct.description ilike 'EKO HOTELS LTD%' then 'Eko Hotels'
        when ct.description ilike 'FLATS FIX%' then 'Flats Fix'
        when ct.description ilike 'WORTHWILD%' then 'Worthwild'
        when ct.description ilike 'PGA ELP%' then 'PGA'
        when ct.description ilike 'MARTINS BBQ JOINT%' then 'Martin''s Bar-B-Que Joint'
        when ct.description ilike 'KILIS KITCHEN%' then 'Kilis Kitchen'
        when ct.description ilike 'SQ *SKULLFADE BARBERS%' then 'Skullfade Barbers'
        when ct.description ilike 'BANGERSAUSTIN.CO%ME&U%' or ct.description ilike 'BANGERSAUSTIN.CO%ME&amp;U%' then 'Banger''s Austin'
        when ct.description ilike 'BOCAS%' then 'Bocas'
        when ct.description ilike 'BEYOND THE PALE NYC%' then 'Beyond the Pale'
        when ct.description ilike 'THEVENTURECRAWLAFTERP%' then 'Venture Crawl Afterparty'
        when ct.description ilike 'ZONA COCINA%' then 'Zona Cocina'
        when ct.description ilike 'Andy%s Greek Taverna%' or ct.description ilike 'Andy?s Greek Taverna%' then 'Andy''s Greek Taverna'
        when ct.description ilike 'RAW HIDE%' then 'Rawhide'
        when ct.description ilike 'GIOIA RISTORANTE %' then 'Gioia Ristorante'
        when ct.description ilike 'Slim Jim%''s Liquor Store%' then 'Slim Jim''s Liquor Store'
        when ct.description ilike 'WHITE RABBIT VENTURES%' then 'White Rabbit Ventures'
        when ct.description ilike 'MCGGETTIGANS DMCC%' then 'McGettigan''s'
        when ct.description ilike 'TOTES ISOTONER%' then 'Totes Isotoner'
        when ct.description ilike 'HELIX PAY%' then 'Helix Pay'
        when ct.description ilike 'WEEKDAY%' then 'Weekday'
        when ct.description ilike 'CENTER PARCS F AND B%' then 'Center Parcs F&B'
        when ct.description ilike 'Good Night Sonny%' then 'Good Night Sonny'
        when ct.description ilike 'SQ *WILDCRAFT KITCHEN%' then 'Wildcraft Kitchen'
        when ct.description ilike 'SALEM EXPRESS LIMO INC%' then 'Salem Express Limo'
        when ct.description ilike 'GOLDEN SANDS Palm%' then 'Golden Sands'
        when ct.description ilike 'DUCK DUCK GOAT%' then 'Duck Duck Goat'
        when ct.description ilike 'JFK BEACON BAR%' then 'JFK Beacon Bar'
        when ct.description ilike 'ETSY  INC.%' or ct.description ilike 'ETSY  INC.%' then 'Etsy'
        when ct.description ilike 'PIANOS%' then 'Pianos'
        when ct.description ilike 'GLORIA''S SEAFOOD CITY%' then 'Gloria''s Seafood City'
        when ct.description ilike 'Ivy Granary Square%' then 'Ivy Granary Square'
        when ct.description ilike 'NW1 DENTAL CARE%' then 'NW1 Dental Care'
        when ct.description ilike 'Vesta Vodafone TopUp%' then 'Vodafone Top Up'
        when ct.description ilike 'O''LEARY''S PUBLIC HOUSE%' then 'O''Leary''s Public House'
        when ct.description ilike 'BAIT MARYAM DMCC%' then 'Bait Maryam'
        when ct.description ilike 'HOUSE OF BLUES CHICAGO%' or ct.description ilike 'HOB CHICAGO%' then 'House of Blues Chicago'
        when ct.description ilike 'THAMES WATER%' then 'Thames Water'
        when ct.description ilike 'LOCKSTOCK % BARREL%' then 'Lock, Stock & Barrel'
        when ct.description ilike 'BLA BLA BEACH CLUB%' then 'Bla Bla Beach Club'
        when ct.description ilike 'KING HEAD%' then 'The King''s Head'
        when ct.description ilike 'EB %' then 'Eventbrite'
        when ct.description ilike 'IL DEP OF REV TAX PYMT%' then 'Illinois Department of Revenue'
        when ct.description ilike 'CAMDEN LOCAL%' then 'Camden Local'
        when ct.description ilike 'COFCO LIMITED%' then 'COFCO Limited'
        when ct.description ilike 'JUMPIN JACKS AT MODERNHAU%' then 'Jumpin Jacks (Modernhaus)'
        when ct.description ilike 'RYMAN %' then 'Ryman'
        when ct.description ilike 'K1 KLUB HOUSE%' then 'K1 Klub House'
        when ct.description ilike 'Sunday*Hole In The Wall%' then 'Hole In The Wall'
        when ct.description ilike 'TOTAL ENERGIES GREENWOOD-%' then 'Total Energies'
        when ct.description ilike 'ROCKY SPORTING CLUB LTD%' then 'Rocky Sporting Club'
        when ct.description ilike 'SQ *ICONOCLAD%' then 'Iconoclad'
        when ct.description ilike 'DINE-IT-4WARD%' then 'Dine-It-4ward'
        when ct.description ilike 'BLACKWELLS%' then 'Blackwell''s'
        when ct.description ilike 'UCHICAGO GIFTS%' then 'UChicago Gifts'
        when ct.description ilike 'HUSTLESASA LIMITED%' then 'HustleSasa'
        when ct.description ilike 'EMPORIO DEL GRANO%' then 'Emporio del Grano'
        when ct.description ilike '24 SEVEN MINI MART LLC%' then '24 Seven Mini Mart'
        when ct.description ilike 'TEXACO %' then 'Texaco'
        when ct.description ilike 'TACBAR JAMAICA%' then 'TAC Bar Jamaica'
        when ct.description ilike 'ZAZA GO SMOKE SHOP%' then 'ZaZa Smoke Shop'
        when ct.description ilike 'SWEETGREEN %' or ct.description ilike 'WWW.SWEETGREEN.COM%' then 'Sweetgreen'
        when ct.description ilike 'LEVY@ %BLACKHAWKS%' then 'Levy (United Center)'
        when ct.description ilike 'HAVANA RESTAURANT%' then 'Havana Restaurant'
        when ct.description ilike 'GARFIELD SUPER SAVE%' then 'Garfield Super Save'
        when ct.description ilike 'Time Out Market Chicago%' then 'Time Out Market Chicago'
        when ct.description ilike 'MAXZI THE GOOD FOOD RESTA%' then 'Maxzi The Good Food'
        when ct.description ilike 'LIQOURAMA FINE%' then 'Liquorama'
        when ct.description ilike 'DRACO RESTAURANTS LLC%' then 'Draco Restaurants'
        when ct.description ilike 'LUKE BRYANS%' then 'Luke Bryan'
        when ct.description ilike 'CARS TAXI SERVICES CO LLC%' then 'Cars Taxi'
        when ct.description ilike 'JFK FLATIRONCOF RSTRS%' then 'Flatiron Coffee (JFK)'
        when ct.description ilike 'AIRPORT RETAIL ENTERPR%' then 'Airport Retail Enterprises'
        when ct.description ilike 'WH Smith Heathrow T3%' or ct.description ilike 'WH Smith Heathrow T3%' then 'WHSmith Heathrow T3'
        when ct.description ilike 'STRAWBERRY HILLS%' then 'Strawberry Hill'
        when ct.description ilike 'PUBLICAN ORD%' then 'Publican (ORD)'
        when ct.description ilike 'MB HOSPITALITY LIMITED%' then 'MB Hospitality'
        when ct.description ilike 'FOUR SEASONS ADORN BAR%' then 'Four Seasons Adorn Bar'
        when ct.description ilike 'GAILS ISLINGTON%' then 'GAIL''s Islington'
        when ct.description ilike 'NAIROBI STREET KITCHEN%' then 'Nairobi Street Kitchen'
        when ct.description ilike 'BIG TIME BOOTS%' then 'Big Time Boots'
        when ct.description ilike 'SSP UK LTD%' then 'SSP UK'
        when ct.description ilike 'JIN BO LAW UK LIMITED%' then 'Jin Bo Law'
        when ct.description ilike 'SQ *P - BAR 3%' then 'P - Bar 3'
        when ct.description ilike 'WHISKEY RIVER%' then 'Whiskey River'
        when ct.description ilike '60 E. LAKE STREET%' then '60 E. Lake Street'
        when ct.description ilike 'FOREVER SALES ENTERPRISE%' then 'Forever Sales Enterprise'
        when ct.description ilike 'LAUNDRYHEAP %' then 'Laundryheap'
        when ct.description ilike 'Terra Sol  Hospitality Se%' then 'Terra Sol Hospitality'
        when ct.description ilike 'SQ *MACDOUGAL STREET ALEH%' then 'MacDougal Street Ale House'
        when ct.description ilike 'BBOOKSTORE ST840%' then 'Bookstore ST840'
        when ct.description ilike 'MANCHU WOK HK ORD%' then 'Manchu Wok (ORD)'
        when ct.description ilike 'SAZERAC PHX%' then 'Sazerac (PHX)'
        when ct.description ilike 'CHANDARANA SUPER%' or ct.description ilike 'CHANDARANA RIVER%' then 'Chandarana Supermarket'
        when ct.description ilike 'PRESSURE SMOKE % VAPE%' then 'Pressure Smoke & Vape'
        when ct.description ilike 'COCK % LION%' then 'Cock & Lion'
        when ct.description ilike 'MCNAMARA AIRP MEZZA%' then 'McNamara Airport Mezzanine'
        when ct.description ilike 'Zettle_*Angel Orient Limi%' then 'Angel Orient (Zettle)'
        when ct.description ilike 'ILSOS CHI CENTRAL DRIV%' or ct.description ilike 'ILSOS INT VEH RENEWAL%' then 'Illinois Secretary of State'
        when ct.description ilike 'SLC UINTA BREWING%' then 'Uinta Brewing'
        when ct.description ilike 'Thai Street Food%' then 'Thai Street Food'
        when ct.description ilike 'NORTH BRIDGE 10 E. GRA%' then 'The Shops at North Bridge (Garage)'
        when ct.description ilike 'HWH DX19 BUDWEISER T3%' then 'Heathrow T3 Budweiser'
        when ct.description ilike 'WHISKEY STREET%' then 'Whiskey Street'
        when ct.description ilike 'Neal''s Yard Dairy%' or ct.description ilike 'Neal''s Yard Dairy - Islin%' then 'Neal''s Yard Dairy'
        when ct.description ilike 'SPUNTINO%' then 'Spuntino'
        when ct.description ilike 'BULL%' then 'The Bull'
        when ct.description ilike 'GREEN PIG PUB%' then 'Green Pig Pub'
        when ct.description ilike 'WASATCH BREWPUB%' then 'Wasatch Brew Pub'
        when ct.description ilike 'SQ *PHILIPPE CONTICINI%' then 'Philippe Conticini'
        when ct.description ilike 'EUPHORIUM BAKERY%' then 'Euphorium Bakery'
        when ct.description ilike 'SUSIE''S FINE BAKED GOODS%' then 'Susie''s Fine Baked Goods'
        when ct.description ilike '4223 ZAROS BAKERY%' then 'Zaro''s Bakery'
        when ct.description ilike 'SQ *P - BAR 2%' then 'P - Bar 2'
        when ct.description ilike 'LGA HUNT AND FISH %' then 'Hunt & Fish (LGA)'
        when ct.description ilike 'CIRCLE K %' then 'Circle K'
        when ct.description ilike 'The Enterprise%' then 'The Enterprise'
        when ct.description ilike 'XS BAR%' then 'XS Bar'
        when ct.description ilike 'TOAD HALL%' then 'Toad Hall'
        when ct.description ilike 'SPANISH COURT HOTEL%' then 'Spanish Court Hotel'
        when ct.description ilike 'ASMARA ENTERTAINMENT WST%' then 'Asmara Entertainment'
        when ct.description ilike 'BUBBLES ORD%' then 'Bubbles (ORD)'
        when ct.description ilike 'DAMN GRAVITY BOOKS%' then 'Damn Gravity Books'
        when ct.description ilike 'NOODLES ETC%' then 'Noodles Etc'
        when ct.description ilike 'Flask%' then 'Flask'
        when ct.description ilike 'R067 HOMEBURGER%' then 'Homeburger'
        when ct.description ilike 'PICKL CATERING SERVICE%' then 'Pickl Catering'
        when ct.description ilike 'Americano%' then 'Americano'
        when ct.description ilike 'HOLLY BUSH%' then 'Holly Bush'
        when ct.description ilike 'Zettle_*Ciaran Hughes%' then 'Ciaran Hughes (Zettle)'
        when ct.description ilike 'V & P FOX LOCKSMITHS LIMI%' then 'V & P Fox Locksmiths'
        when ct.description ilike 'WHITE HORSE 066141%' then 'White Horse'
        when ct.description ilike 'HUDSONLOND* TAXIHUDSON%' then 'Hudson London Taxi'
        when ct.description ilike 'BENS PIZZERIA%' then 'Ben''s Pizzeria'
        when ct.description ilike 'WIFIONBOARD%' then 'WiFi Onboard'
        when ct.description ilike 'MISTER WRIGHT FINE WINES%' then 'Mister Wright Fine Wines'
        when ct.description ilike 'COMMONS CLUB%' then 'Commons Club'
        when ct.description ilike 'JFK PALM REST %' then 'Palm Restaurant (JFK)'
        when ct.description ilike 'SQ *SEOUL TACO HYDE PARK%' then 'Seoul Taco'
        when ct.description ilike 'THE RIVER CAFE LTD%' then 'The River Cafe'
        when ct.description ilike 'SUPER KILIMANJARO ENT%' then 'Super Kilimanjaro Entertainment'
        when ct.description ilike 'MR. QUILES MEXICAN FOO%' then 'Mr. Quiles Mexican Food'
        when ct.description ilike 'OPENMOVE - TRANSPORT%' then 'OpenMove'
        when ct.description ilike 'UNSEEN NAIROBI%' then 'Unseen Nairobi'
        when ct.description ilike 'WHITE HORSE SPIRITS %' then 'White Horse Spirits'
        when ct.description ilike 'TOM-Ground Bar%' then 'Ground Bar'
        when ct.description ilike 'STAGE DOOR DELI%' then 'Stage Door Deli'
        when ct.description ilike 'HMS Host International%' then 'HMSHost'
        when ct.description ilike 'FRONTERA GRILL HK ORD%' then 'Frontera Grill (ORD)'
        when ct.description ilike 'SQ *SHOREDITCH%' then 'Shoreditch'
        when ct.description ilike 'SQ *CHICAGO SPECIAL EVENT%' then 'Chicago Special Event (Square)'
        when ct.description ilike 'FEDERALES%' then 'Federales'
        when ct.description ilike 'MOCHINUT (CHICAGO DOWN%' then 'Mochinut (Chicago)'
        when ct.description ilike 'WOLFGANG PUCK%' then 'Wolfgang Puck'
        when ct.description ilike 'TECH SOCIAL%' then 'Tech Social'
        when ct.description ilike 'LANGES LIQUORS%' then 'Lange''s Liquors'
        when ct.description ilike 'BAO Soho - Takeaway%' then 'BAO Soho'
        when ct.description ilike 'DINES* BRCKWL WHOLEF%' then 'Dines (Brockwell)'
        when ct.description ilike 'HANA GROUP INC%' then 'Hana Group'
        when ct.description ilike '4222 HILL COUNTRY%' then 'Hill Country'
        when ct.description ilike 'SQ *BB&K LIMITED%' or ct.description ilike 'SQ *BB&amp;K LIMITED%' then 'BB&K Limited'
        when ct.description ilike 'SQ *URBAN PINE EATERY%' then 'Urban Pine Eatery'
        when ct.description ilike 'MORPHEUS VENTURES LIMIT%' then 'Morpheus Ventures'
        when ct.description ilike 'CIRCLE OFF LICENCE%' then 'Circle Off Licence'
        when ct.description ilike 'TWOGRAPES LIMITED%' then 'Two Grapes'
        when ct.description ilike 'Zettle_*SEND COFFEE%' then 'Send Coffee'
        when ct.description ilike 'THE JACKALOPE%' then 'The Jackalope'
        when ct.description ilike 'DYLAN MURPHY`S%' or ct.description ilike 'DYLAN MURPHY''S%' then 'Dylan Murphy''s'
        when ct.description ilike 'Benita Bakery%' then 'Benita Bakery'
        when ct.description ilike 'SOCK CITY - PARK CITY%' then 'Sock City'
        when ct.description ilike 'SQ *THE SOUVLAKI GREEK GR%' then 'The Souvlaki Greek Grill'
        when ct.description ilike 'MOBIFIX GADGETS LIMITED%' then 'Mobifix Gadgets'
        when ct.description ilike 'SQ *PICNIC%' then 'Picnic (Square)'
        when ct.description ilike 'BOOTS %' then 'Boots'
        when ct.description ilike 'AUGUST SUN INVESTMENTS%' then 'August Sun Investments'
        when ct.description ilike 'G & G ATLANTIC LLC%' or ct.description ilike 'G &amp; G ATLANTIC LLC%' then 'G & G Atlantic'
        when ct.description ilike 'SQ *LEVAIN BAKERY%' then 'Levain Bakery'
        when ct.description ilike 'ANGEL VAPE%' then 'Angel Vape'
        when ct.description ilike 'SPO*C''ESTLAVIECAFE%' then 'C''est La Vie Cafe'
        when ct.description ilike 'Vinegar Yard%' then 'Vinegar Yard'
        when ct.description ilike 'KEBAB EMPIRE%' then 'Kebab Empire'
        when ct.description ilike 'Nyx*Nuts on Clark Inc.%' or ct.description ilike 'NUTS ON CLARK OHARE AIRPO%' or ct.description ilike 'STARBUCKS H06 ORD%' then 'Nuts on Clark'
        when ct.description ilike 'PDL BARBERSHOP%' then 'PDL Barbershop'
        when ct.description ilike 'PDL COFFEE CO.%' then 'PDL Coffee Co.'
        when ct.description ilike 'CANAL EXPRESS INC%' then 'Canal Express'
        when ct.description ilike 'WORLDS END (FINSBU%' then 'World''s End (Finsbury)'
        when ct.description ilike 'SMITHFIELD HALL%' then 'Smithfield Hall'
        when ct.description ilike 'King Of Falael%' or ct.description ilike 'KING OF FALAFEL%' then 'King of Falafel'
        when ct.description ilike 'RED ROCK BREWING SLC%' then 'Red Rock Brewing'
        when ct.description ilike 'JACK TAXI* JACKTAXI%' then 'Jack Taxi'
        when ct.description ilike 'COFFEE GARDEN LLC%' then 'Coffee Garden'
        when ct.description ilike '9TH SKY HIGH CORPORATION%' then '9th Sky High'
        when ct.description ilike 'SQ *CAFE TOLA LTD.%' then 'Cafe Tola'
        when ct.description ilike '11 PLC - HOSPITALITY%' then '11 Plc Hospitality'
        when ct.description ilike 'LINCOLN PARK ZOO CONCE%' then 'Lincoln Park Zoo (Concessions)'
        when ct.description ilike 'STICKK.COM%' then 'stickK'
        when ct.description ilike 'SSP NEDERLAND B.V.%' then 'SSP Nederland'
        when ct.description ilike '4b  ADEKUNLE%' or ct.description ilike '4b  ADEKUNLE%' then '4B Adekunle'
        when ct.description ilike 'SALISBURY%' then 'The Salisbury'
        when ct.description ilike 'PORCUPINE%' then 'The Porcupine'
        when ct.description ilike 'Roros Co Limited KE%' then 'Roros Co Limited'
        when ct.description ilike 'SumUp  *UDDERLICIOUS L%' then 'Udderlicious (SumUp)'
        when ct.description ilike 'TRG  HOLDINGS  LIMITED%' then 'TRG Holdings'
        when ct.description ilike 'CAMDEN EYE%' then 'Camden Eye'
        when ct.description ilike 'CRYSTAL EDGE RESTAURANT%' then 'Crystal Edge Restaurant'
        when ct.description ilike 'ANGLO AFRICAN PROPERTY HO%' then 'Anglo African Property Holdings'
        when ct.description ilike 'SumUp  *Tunde otukoya%' then 'Tunde Otukoya (SumUp)'
        when ct.description ilike 'STGCOACH/CTYLINK%' then 'Stagecoach / Citylink'
        when ct.description ilike 'PY *FARMAIR MARKET-CHICAG%' then 'FarmAir Market'
        when ct.description ilike 'PYD*Camden Road Arms%' then 'Camden Road Arms'
        when ct.description ilike 'CAFE BLUE - Irish Town%' then 'Cafe Blue'
        when ct.description ilike 'Fitzbillies Cambridge L%' then 'Fitzbillies'
        when ct.description ilike 'EAST VILLAGE PIZZA%' then 'East Village Pizza'
        when ct.description ilike 'THINGS REMEMBERED NIG LTD%' then 'Things Remembered (NG)'
        when ct.description ilike 'FOXTROT MARKET-WEST LOOP%' then 'Foxtrot Market'
        when ct.description ilike 'PRIMARK %' then 'Primark'
        when ct.description ilike 'SP THE FIG TREE CHIC%' then 'The Fig Tree (Chicago)'
        when ct.description ilike 'EE LTD%' then 'EE'
        when ct.description ilike 'THE ABBEY RESORT %' then 'The Abbey Resort'
        when ct.description ilike 'SQ *NASHRIN MATIN%' then 'Nashrin Matin'
        when ct.description ilike 'CTLP*BAR PARTNERS INC%' then 'Bar Partners Inc'
        when ct.description ilike 'UOFC STUDENT CNTRS PUB%' then 'UChicago Student Centers Pub'
        when ct.description ilike 'GROVE ORD ROCKY MOUNT%' then 'Grove (ORD)'
        when ct.description ilike 'ORIGINAL ROMA PIZZA%' then 'Original Roma Pizza'
        when ct.description ilike 'THE DRAKE RESTAURANT%' then 'The Drake Restaurant'
        when ct.description ilike 'SIMPLY FRESH%' then 'Simply Fresh'
        when ct.description ilike 'NOHEA CAFE%' then 'Nohea Cafe'
        when ct.description ilike 'LONDON EASTCHEAP ST%' then 'London Eastcheap Street'
        when ct.description ilike 'BOTTEGA PROSECCO BAR %' then 'Bottega Prosecco Bar'
        when ct.description ilike 'Mattheessens%' then 'Mattheessens'
        when ct.description ilike 'SQ *WIRED CO.%' then 'Wired Co.'
        when ct.description ilike 'CITY OF FLAGSTAFF FLAG%' then 'City of Flagstaff'
        when ct.description ilike 'MBE LONDON HIGHBURY AND I%' then 'Mail Boxes Etc. (Highbury & Islington)'
        when ct.description ilike 'ARTCAFFE COFFEE AND BAK%' then 'Artcaffe'
        when ct.description ilike 'PCS*TiP JAR%' then 'Tip Jar'
        when ct.description ilike 'CTYCHGO*SERVICEFEES%' or ct.description ilike 'CITY CHICAGO TICKET WEB%' or ct.description ilike 'CTY CLERK STICKERS%' or ct.description ilike 'CTYCHGO CLK STICKER%' then 'City of Chicago'
        when ct.description ilike 'SUMMIT RETAIL %' then 'SUMMIT Retail'
        when ct.description ilike 'GIFT BASKETS%' then 'Gift Baskets'
        when ct.description ilike 'ARDEN  BARBERSHOP%' then 'Arden Barbershop'
        when ct.description ilike 'MANDARIN ORIENTAL%' then 'Mandarin Oriental'
        when ct.description ilike 'MARKET STREET GRILL CO%' then 'Market Street Grill'
        when ct.description ilike 'PHEBES TAVERN AND GRILL%' then 'Phebe''s Tavern'
        when ct.description ilike 'THE BERKSHIRE ROOM%' then 'The Berkshire Room'
        when ct.description ilike 'SPO*GRANDCRU%' then 'Grand Cru'
        when ct.description ilike 'NOLA EATERY % SOCIAL%' then 'Nola Eatery & Social House'
        when ct.description ilike 'UOFC WOLFGANG%' then 'UChicago - Wolfgang Puck'
        when ct.description ilike 'LIQUOR BAR K10 ORD%' or ct.description ilike 'LIQUOR BAR C06 ORD%' then 'Liquor Bar (ORD)'

        ------------------------------------------------------------------
        -- RETAIL / APPAREL / ELECTRONICS
        ------------------------------------------------------------------
        when ct.description ilike 'MACYS %' or ct.description ilike 'MACYS  STATE STREET%' then 'Macy''s'
        when ct.description ilike 'BLOOMINGDALES%' then 'Bloomingdale''s'
        when ct.description ilike 'LULULEMON %' then 'Lululemon'
        when ct.description ilike 'NikePOS_US%' then 'Nike'
        when ct.description ilike 'Hugo Boss %' then 'Hugo Boss'
        when ct.description ilike 'TARGET        %' or ct.description ilike 'TARGET %' then 'Target'
        when ct.description ilike 'WL *Steam Purchase%' then 'Steam'
        when ct.description ilike 'IKEA CHICAGO%' then 'IKEA'
        when ct.description ilike 'AMZNMktplace%' then 'Amazon'
        when ct.description ilike 'LIBERTY%' then 'Liberty London'

        ------------------------------------------------------------------
        -- GAS / AUTO
        ------------------------------------------------------------------
        when ct.description ilike 'BP#%' then 'BP'
        when ct.description ilike 'EXXON %' then 'Exxon'
        when ct.description ilike 'TOYOTA OF LINCOLN PARK%' then 'Toyota of Lincoln Park'
        when ct.description ilike 'BERTS CAR WASH%' then 'Bert''s Car Wash'

        ------------------------------------------------------------------
        -- SHIPPING / COURIER
        ------------------------------------------------------------------
        when ct.description ilike 'FEDEX%' then 'FedEx'

        ------------------------------------------------------------------
        -- ADDITIONAL LONG-TAIL PATCHES (INSERT THIS BLOCK RIGHT AFTER FEDEX)
        ------------------------------------------------------------------
        -- Furniture / Home
        when ct.description ilike 'CORT FURNITURE RENTAL%' then 'CORT Furniture'
        when ct.description ilike 'CORT FURNITURE RNTL%'  then 'CORT Furniture'

        -- AAA / Insurance / Memberships
        when ct.description ilike 'AAA INSURANCE ECOM%'      then 'AAA'
        when ct.description ilike 'AAA ACG NE0069 EFT RCC%'  then 'AAA'
        when ct.description ilike 'AAA ACG MI0965 AAA.COM%'  then 'AAA'
        when ct.description ilike 'AAA ACG MI0967 POC MEMBR%' then 'AAA'
        when ct.description ilike 'AAA CLUB/INSUR %'         then 'AAA'
        when ct.description ilike 'AAA INSURANCE GW EFT%'     then 'AAA'

        -- Verizon / AT&T
        when ct.description ilike 'VZWRLSS*APOCC VISN%' then 'Verizon Wireless'
        when ct.description ilike 'ATT*BILL PAYMENT%'   then 'AT&T'
        when ct.description ilike 'ATT*BILL PAYMENT 800-288-2020 ,TX%' then 'AT&T'
        when ct.description ilike 'ATT*BILL PAYMENT         800-288-2020 TX%' then 'AT&T'
        when ct.description ilike 'ATT*BILL PAYMENT         XXX-XXX-2020 TX%' then 'AT&T'

        -- Tock / Smyth / Next
        when ct.description ilike 'TOCK ATNEXT%'      then 'Next'
        when ct.description ilike 'TOCK AT*SMYTH%'    then 'Smyth / The Loyalist'
        when ct.description ilike 'PY *SMYTH THE LOYALIST%' then 'Smyth / The Loyalist'
        when ct.description ilike 'NEXT%'             then 'Next'

        -- Delivery
        when ct.description ilike 'DELIVEROO%'        then 'Deliveroo'

        -- One-offs called out
        when ct.description ilike 'LAYLA GRILL%'      then 'Layla Grill'
        when ct.description ilike 'OVA%'              then 'Ova'
        when ct.description ilike 'DMN/BALLIEBALLERSONSHO%' then 'Ballie Ballerson (Shoreditch)'
        when ct.description ilike '59 MURRAY ENTERPRISES%'  then 'FlashDancers'
        when ct.description ilike 'ET CAR HIRE%'      then 'ET Car Hire'
        when ct.description ilike 'SPORTS & DIVER CLUB LI%'  then 'Sports & Diver Club'
        when ct.description ilike 'SPORTS &amp; DIVER CLUB LI%' then 'Sports & Diver Club'
        when ct.description ilike 'CHICAGO TOUCH%'    then 'Chicago Touch'
        when ct.description ilike 'MIDTOWN CAFE%'     then 'Midtown Cafe'
        when ct.description ilike 'DELIS SUPERMARKET %COFF%' or ct.description ilike 'DELIS SUPERMARKET &amp;COFF%' then 'Delis Supermarket & Coffee'
        when ct.description ilike 'WEST LOOP CLEANERS%' then 'West Loop Cleaners'
        when ct.description ilike 'MADEWELL %'        then 'Madewell'
        when ct.description ilike 'EASTSIDE AMSTAR%'  then 'Eastside Amstar'
        when ct.description ilike 'BLIND BARBER%'     then 'Blind Barber'
        when ct.description ilike 'SHAKESPEARES HEAD%' then 'Shakespeare''s Head'
        when ct.description ilike 'HIGHJUMPCHICAGO.ORG%' then 'HighJump Chicago'
        when ct.description ilike 'BEAUTY & ESSEX - NEW Y%' or ct.description ilike 'BEAUTY &amp; ESSEX - NEW Y%' then 'Beauty & Essex'
        when ct.description ilike 'BINNYS EXPRESS %'  then 'Binny''s'
        when ct.description ilike '10522 ASPEN PLACE FLAG%' then 'Aspen Place (Flagstaff)'
        when ct.description ilike 'UC HUB %'          then 'UC Hub'
        when ct.description ilike 'JOHN LEWIS%'       then 'John Lewis'
        when ct.description ilike 'THE DUTCH%'        then 'The Dutch'
        when ct.description ilike 'ALLIANCE BAKERY%'  then 'Alliance Bakery'
        when ct.description ilike 'ELEPHANT % CASTLE WABASH%' or ct.description ilike 'ELEPHANT &amp; CASTLE WABASH%' then 'Elephant & Castle (Wabash)'
        when ct.description ilike 'P L P EVENTS%'     then 'PLP Events'
        when ct.description ilike 'BLACKLOCK CANARY WHARF%' then 'Blacklock Canary Wharf'
        when ct.description ilike 'IL VIZIETTO DI CORTINA%' then 'Il Vizietto di Cortina'
        when ct.description ilike 'LEMONADE I* LEMONADE I%' then 'Lemonade'
        when ct.description ilike 'LEMONADE INSURANCE%'     then 'Lemonade'
        when ct.description ilike 'RENEE MALLS LTD%'  then 'Renee Malls Ltd'
        when ct.description ilike 'Phoenicia Mediterranean F%' then 'Phoenicia Mediterranean'
        when ct.description ilike 'GOOSE ISLAND L10 ORD%' then 'Goose Island (ORD)'
        when ct.description ilike 'Granger  Co.%'     then 'Granger Co.'
        when ct.description ilike 'WEST LOOP  IL - PIC%' then 'West Loop - PIC'
        when ct.description ilike 'NGImmigrationVisa%' then 'NG Immigration Visa'
        when ct.description ilike 'COURSRA*%'         then 'Coursera'
        when ct.description ilike '72808 - CITYFRONT GARAGE%' then 'Cityfront Garage'
        when ct.description ilike 'ARLO CHICAGO F&B%' or ct.description ilike 'ARLO CHICAGO F&amp;B%' then 'ARLO Chicago (F&B)'
        when ct.description ilike 'UNCORKED 2017 Limited%' then 'Uncorked 2017'
        when ct.description ilike 'EWR C1 ABRUZZO%'   then 'Abruzzo (EWR C1)'
        when ct.description ilike 'LA VITA E BELLA%'  then 'La Vita e Bella'
        when ct.description ilike 'MUZE CLUB%'        then 'Muze Club'
        when ct.description ilike 'SQ *OLYMPUS HILLS LANES%' or ct.description ilike 'OLYMPUS HILLS BOWLING LAN%' then 'Olympus Hills Bowling Lanes'
        when ct.description ilike 'PROHIBITION BARBER CO%' then 'Prohibition Barber Co'
        when ct.description ilike 'EVA%'              then 'EVA'
        when ct.description ilike 'MATTORIS OPEN MARKET%' then 'Mattori''s Open Market'
        when ct.description ilike 'BETA GAMMA SIGMA%' then 'Beta Gamma Sigma'
        when ct.description ilike 'SQ *HOUSE OF YES%' then 'House of Yes'
        when ct.description ilike 'GOOGLE *Google One%' then 'Google One'
        when ct.description ilike 'SQ *MAYHEM BEER % SANDWIC%' or ct.description ilike 'SQ *MAYHEM BEER &amp; SANDWIC%' then 'Mayhem Beer & Sandwiches'
        when ct.description ilike 'WWW.GUGGENHEIM.ORG%' or ct.description ilike 'RA@GUGGENHEIM%' then 'Guggenheim Museum'
        when ct.description ilike 'ART INST CHGO-ONLINE%' or ct.description ilike 'ART INST-MW MUS SHOP%' then 'Art Institute of Chicago'
        when ct.description ilike 'SQ *TINY TAPP % CAFE%' then 'Tiny Tapp & Cafe'
        when ct.description ilike 'JFK LEGRAND COMPTOIR %'  then 'Le Grand Comptoir (JFK)'
        when ct.description ilike 'SQ *LYRIC THEATRE%'      then 'Lyric Theatre'
        when ct.description ilike 'SQ *SALT LAKE ROASTING CO%' then 'Salt Lake Roasting Co'
        when ct.description ilike 'V & P FOX LOCKSMITHS LIMI%' or ct.description ilike 'V &amp; P FOX LOCKSMITHS LIMI%' then 'V & P Fox Locksmiths'
        when ct.description ilike 'THE BULL%'           then 'The Bull'
        when ct.description ilike 'PY *LAYLAS%'         then 'Layla''s'
        when ct.description ilike 'GOOSE ISLAND BAR ORD%' then 'Goose Island (ORD)'
        when ct.description ilike 'SQ *GNOCCHI ON 9TH%' then 'Gnocchi on 9th'
        when ct.description ilike 'COA PARKS % REC%' or ct.description ilike 'COA PARKS &amp; REC%' then 'City of Austin Parks & Rec'
        when ct.description ilike 'RIFUGIO NUVOLAU%'   then 'Rifugio Nuvolau'
        when ct.description ilike 'Waterloo Tap%'      then 'Waterloo Tap'
        when ct.description ilike 'THE CASE CENTRE%'   then 'The Case Centre'
        when ct.description ilike 'NIGERIAN CONSERVATION FOU%' then 'Nigerian Conservation Foundation'
        when ct.description ilike 'SMOKE POST LOOP%'   then 'Smoke Post'
        when ct.description ilike 'SQ *THE GALLIVAN CENTER%' then 'The Gallivan Center'

        when ct.description ilike '%Kasa Living%' then 'Kasa Living'
        when ct.description ilike '%Booth Campus Groups%' then 'Booth Groups'
        when ct.description ilike '%SIMPLY FOOD - SSP%' then 'Marks and Spencer'

        ------------------------------------------------------------------
        -- FINANCE / INVESTING (if any slip past your payment filter)
        ------------------------------------------------------------------
        when ct.description ilike 'ROBINHOOD DEBITS%' then 'Robinhood'
        when ct.description ilike 'EDWARD JONES INVESTMENT%' then 'Edward Jones'

        ------------------------------------------------------------------
        -- FALLBACKS
        ------------------------------------------------------------------
        -- Any unclassified Toast/Shift4 “TST* …” line = Restaurants (misc)
        when ct.description ilike 'TST*%' or ct.description ilike 'TST-%'then 'Restaurants (misc)'

        else 'Uncategorized'
    end merchant_name_modified
, sum(ct.amount) total_spend
, sum(sum(ct.amount)) over () cumulative_spend
, sum(ct.amount) / sum(sum(ct.amount)) over () percent_spend
from
    public.card_transactions ct
where
    true
    and case
        when ct.type is not null then ct.type
        when ct.card_last4 not in (3221, 4245, 5083, 6823) then 'Payment'
        when ct.description ilike '%Online Transfer%' then 'Payment'
        when ct.description ilike '%Edward Jones%' then 'Payment'
        when ct.description ilike '%JPMorgan Chase%' then 'Payment'
        when ct.description ilike '%Fedwire%' then 'Payment'
        when ct.description ilike '%Automatic Payment%' then 'Payment'
        else 'Sale'
    end = 'Sale'
group by
    1

order by
    total_spend asc